[package]
name = "pig"
version = "0.1.0"
edition = "2024"

[dependencies]
my_library = { package = "my_library", path = "../my_library", features = [
  "locking",
] }
bevy = { workspace = true }
bevy_egui = { workspace = true }
