[package]
name = "my_library"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9"

[dev-dependencies]

criterion = { version = "0.7", features = ["html_reports"] }

[[bench]]
name = "random"
harness = false
